networks:
  openclaw-net:
    driver: bridge

services:
  openclaw-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OPENCLAW_QMD_CUDA=${OPENCLAW_QMD_CUDA:-false}
    image: openclaw:custom
    networks:
      - openclaw-net
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_CONFIG_PATH: ${OPENCLAW_CONFIG_HOST:-/home/node/.openclaw}/openclaw.json
      OPENCLAW_STATE_DIR: ${OPENCLAW_CONFIG_HOST:-/home/node/.openclaw}
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN:-}
      TZ: ${OPENCLAW_TZ:-UTC}
      NODE_LLAMA_CPP_CUDA: ${OPENCLAW_QMD_CUDA:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${OPENCLAW_CONFIG_HOST:-/home/node/.openclaw}:${OPENCLAW_CONFIG_HOST:-/home/node/.openclaw}
      - .:/app/ClawDev
    group_add:
      - ${DOCKER_GID:-1001}
    ports:
      - "${OPENCLAW_GATEWAY_PORT:-18789}:18789"
      - "${OPENCLAW_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "${OPENCLAW_GATEWAY_BIND:-lan}",
        "--port",
        "18789",
      ]
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://127.0.0.1:18789/healthz').then((r)=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))",
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  gitea:
    image: gitea/gitea:latest
    container_name: roger-gitea
    restart: always
    networks:
      - openclaw-net
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__HTTP_PORT=3000
#      - GITEA__server__SSH_PORT=2424
#      - GITEA__server__SSH_LISTEN_PORT=22
      - GITEA__server__ROOT_URL=http://host.docker.internal:3000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__actions__ENABLED=false        # 不需要 Actions，关掉省资源
      - TZ=${OPENCLAW_TZ:-UTC}
      - GITEA__repository__FORCE_PRIVATE=false
      - GITEA__repository__DEFAULT_PRIVATE=public
      - GITEA__service__ALLOW_ONLY_INTERNAL_REGISTRATION=true
      - GITEA__repository__DEFAULT_PUSH_CREATE_PRIVATE=false
    ports:
      - "3000:3000"
#      - "2424:22"
    volumes:
      - ./volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
